"""A2A protocol code generation for LangChain/LangGraph agents."""

from vystak.schema.agent import Agent


def generate_agent_card_code(agent: Agent) -> str:
    """Generate AGENT_CARD dict constant and /.well-known/agent.json endpoint."""
    description = (
        (agent.instructions or agent.name)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    skills_list = [skill.name for skill in agent.skills]

    lines = []
    lines.append("# A2A Agent Card")
    lines.append("AGENT_CARD = {")
    lines.append(f'    "name": "{agent.name}",')
    lines.append(f'    "description": "{description}",')
    lines.append('    "url": "http://localhost:8000",')
    lines.append('    "version": "0.1.0",')
    lines.append('    "capabilities": {')
    lines.append('        "streaming": True,')
    lines.append('        "pushNotifications": False,')
    lines.append('        "stateTransitionHistory": False,')
    lines.append("    },")
    lines.append('    "skills": [')
    for skill_name in skills_list:
        lines.append("        {")
        lines.append(f'            "id": "{skill_name}",')
        lines.append(f'            "name": "{skill_name}",')
        lines.append("        },")
    lines.append("    ],")
    lines.append(f'    "models": ["vystak/{agent.name}"],')
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append('@app.get("/.well-known/agent.json")')
    lines.append("async def agent_card():")
    lines.append("    return AGENT_CARD")
    lines.append("")

    return "\n".join(lines)


def generate_task_manager_code() -> str:
    """Generate TaskManager class with in-memory task storage."""
    lines = []
    lines.append("# A2A Task Manager")
    lines.append("_task_manager = None")
    lines.append("")
    lines.append("")
    lines.append("class TaskManager:")
    lines.append('    """In-memory task manager for A2A protocol."""')
    lines.append(
        "    # Task states: submitted, working, input_required, completed, canceled, failed"
    )
    lines.append("")
    lines.append("    def __init__(self):")
    lines.append("        self._tasks = {}")
    lines.append("")
    lines.append("    def create_task(self, task_id: str, message: dict) -> dict:")
    lines.append('        """Create a new task with submitted state."""')
    lines.append("        task = {")
    lines.append('            "id": task_id,')
    lines.append('            "status": {')
    lines.append('                "state": "submitted",')
    lines.append("            },")
    lines.append('            "history": [message],')
    lines.append("        }")
    lines.append("        self._tasks[task_id] = task")
    lines.append("        return task")
    lines.append("")
    lines.append("    def get_task(self, task_id: str) -> dict | None:")
    lines.append('        """Get a task by ID."""')
    lines.append("        return self._tasks.get(task_id)")
    lines.append("")
    lines.append(
        "    def update_task(self, task_id: str, state: str, result: str | None = None) -> dict | None:"
    )
    lines.append('        """Update task state and optionally set result."""')
    lines.append("        task = self._tasks.get(task_id)")
    lines.append("        if task is None:")
    lines.append("            return None")
    lines.append('        task["status"]["state"] = state')
    lines.append("        if result is not None:")
    lines.append('            task["status"]["message"] = {')
    lines.append('                "role": "agent",')
    lines.append('                "parts": [{"text": result}],')
    lines.append("            }")
    lines.append("        return task")
    lines.append("")
    lines.append("")
    lines.append("_task_manager = TaskManager()")
    lines.append("")

    return "\n".join(lines)


def generate_a2a_handler_code(agent: Agent) -> str:
    """Generate the /a2a POST endpoint and JSON-RPC dispatcher.

    Emits source that constructs a ``vystak.transport.A2AHandler`` from two
    local callables (``_a2a_one_shot`` and ``_a2a_streaming``) and dispatches
    through it from the FastAPI ``/a2a`` route. No behavioural change — same
    JSON-RPC envelope, same SSE events. Setting up for non-HTTP transports
    to re-use the handler via their listener implementations.
    """
    lines = []

    # Imports
    lines.append("from langgraph.types import Command")
    lines.append("from fastapi import Request")
    lines.append("from vystak.transport import A2AEvent, A2AHandler, A2AMessage, A2AResult")
    lines.append("")
    lines.append("")

    # --- One-shot callable (wraps LangGraph ainvoke) ---
    lines.append("async def _a2a_one_shot(message: A2AMessage, metadata: dict) -> str:")
    lines.append('    """Invoke the agent one-shot and return the final text.')
    lines.append("")
    lines.append("    Uses ``message.correlation_id`` as the A2A task id; reads/writes task state")
    lines.append(
        "    via the module-level ``_task_manager`` so interrupt/resume flow is preserved."
    )
    lines.append('    """')
    lines.append("    task_id = message.correlation_id or str(uuid.uuid4())")
    lines.append('    session_id = metadata.get("sessionId") or task_id')
    lines.append("")
    lines.append("    # Extract context from metadata (propagated from caller agent)")
    lines.append('    trace_id = metadata.get("trace_id") or str(uuid.uuid4())')
    lines.append('    user_id = metadata.get("user_id")')
    lines.append('    project_id = metadata.get("project_id")')
    lines.append('    parent_task_id = metadata.get("parent_task_id")')
    lines.append("")
    lines.append("    # Ensure a task exists and transition it to 'working'.")
    lines.append("    existing = _task_manager.get_task(task_id)")
    lines.append("    if existing is None:")
    lines.append("        _task_manager.create_task(task_id, {")
    lines.append('            "role": message.role,')
    lines.append('            "parts": message.parts,')
    lines.append("        })")
    lines.append('    _task_manager.update_task(task_id, "working")')
    lines.append("")
    lines.append("    # Extract text from message parts")
    lines.append('    text = " ".join(p.get("text", "") for p in message.parts if "text" in p)')
    lines.append("")
    lines.append("    # Build config with propagated context")
    lines.append('    config = {"configurable": {')
    lines.append('        "thread_id": session_id,')
    lines.append('        "trace_id": trace_id,')
    lines.append('        "user_id": user_id,')
    lines.append('        "project_id": project_id,')
    lines.append('        "parent_task_id": parent_task_id,')
    lines.append('        "agent_name": AGENT_NAME,')
    lines.append("    }}")
    lines.append("")
    lines.append("    # Check if task is in input_required state (resume scenario)")
    lines.append("    existing = _task_manager.get_task(task_id)")
    lines.append('    current_state = existing["status"]["state"] if existing else None')
    lines.append("")
    lines.append('    if current_state == "input_required":')
    lines.append("        agent_input = Command(resume=text)")
    lines.append("    else:")
    lines.append('        agent_input = {"messages": [("user", text)]}')
    lines.append("")
    lines.append("    try:")
    lines.append("        result = await _agent.ainvoke(")
    lines.append("            agent_input,")
    lines.append("            config=config,")
    lines.append("        )")
    lines.append("")
    lines.append("        # Check for interrupt / input_required")
    lines.append('        if "__interrupt__" in result:')
    lines.append('            interrupt_value = result["__interrupt__"]')
    lines.append(
        '            interrupt_text = str(interrupt_value[0].value) if interrupt_value else "Input required"'
    )
    lines.append('            _task_manager.update_task(task_id, "input_required", interrupt_text)')
    lines.append("            return interrupt_text")
    lines.append("")
    lines.append('        content = result["messages"][-1].content')
    lines.append("        if isinstance(content, list):")
    lines.append('            response_text = "".join(')
    lines.append('                block.get("text", "") if isinstance(block, dict) else str(block)')
    lines.append("                for block in content")
    lines.append("            )")
    lines.append("        else:")
    lines.append("            response_text = str(content)")
    lines.append('        _task_manager.update_task(task_id, "completed", response_text)')
    lines.append("        return response_text")
    lines.append("    except Exception as exc:")
    lines.append('        _task_manager.update_task(task_id, "failed", str(exc))')
    lines.append("        raise")
    lines.append("")
    lines.append("")

    # --- Streaming callable (wraps LangGraph astream_events) ---
    lines.append("async def _a2a_streaming(message: A2AMessage, metadata: dict):")
    lines.append('    """Stream ``A2AEvent`` values from the agent.')
    lines.append("")
    lines.append("    Emits:")
    lines.append('      * ``A2AEvent(type="token", text=...)`` per streamed chunk')
    lines.append(
        '      * ``A2AEvent(type="status", data={"state": "input_required", ...}, final=True)``'
    )
    lines.append("        on interrupt")
    lines.append('      * ``A2AEvent(type="final", text=response_text, final=True)`` on completion')
    lines.append('    """')
    lines.append("    task_id = message.correlation_id or str(uuid.uuid4())")
    lines.append('    session_id = metadata.get("sessionId") or task_id')
    lines.append("")
    lines.append("    # Extract context from metadata")
    lines.append('    trace_id = metadata.get("trace_id") or str(uuid.uuid4())')
    lines.append('    user_id = metadata.get("user_id")')
    lines.append('    project_id = metadata.get("project_id")')
    lines.append('    parent_task_id = metadata.get("parent_task_id")')
    lines.append("")
    lines.append("    # Ensure a task exists and transition it to 'working'.")
    lines.append("    existing = _task_manager.get_task(task_id)")
    lines.append("    if existing is None:")
    lines.append("        _task_manager.create_task(task_id, {")
    lines.append('            "role": message.role,')
    lines.append('            "parts": message.parts,')
    lines.append("        })")
    lines.append('    _task_manager.update_task(task_id, "working")')
    lines.append("")
    lines.append("    # Extract text from message parts")
    lines.append('    text = " ".join(p.get("text", "") for p in message.parts if "text" in p)')
    lines.append("")
    lines.append("    # Build config with propagated context")
    lines.append('    config = {"configurable": {')
    lines.append('        "thread_id": session_id,')
    lines.append('        "trace_id": trace_id,')
    lines.append('        "user_id": user_id,')
    lines.append('        "project_id": project_id,')
    lines.append('        "parent_task_id": parent_task_id,')
    lines.append('        "agent_name": AGENT_NAME,')
    lines.append("    }}")
    lines.append("")
    lines.append("    # Check if task is in input_required state (resume scenario)")
    lines.append("    existing = _task_manager.get_task(task_id)")
    lines.append('    current_state = existing["status"]["state"] if existing else None')
    lines.append("")
    lines.append('    if current_state == "input_required":')
    lines.append("        agent_input = Command(resume=text)")
    lines.append("    else:")
    lines.append('        agent_input = {"messages": [("user", text)]}')
    lines.append("")
    lines.append("    accumulated = []")
    lines.append("    try:")
    lines.append("        async for event in _agent.astream_events(")
    lines.append("            agent_input,")
    lines.append("            config=config,")
    lines.append('            version="v2",')
    lines.append("        ):")
    lines.append('            if "__interrupt__" in event:')
    lines.append('                interrupt_value = event["__interrupt__"]')
    lines.append(
        '                interrupt_text = str(interrupt_value[0].value) if interrupt_value else "Input required"'
    )
    lines.append(
        '                _task_manager.update_task(task_id, "input_required", interrupt_text)'
    )
    lines.append("                yield A2AEvent(")
    lines.append('                    type="status",')
    lines.append("                    text=interrupt_text,")
    lines.append('                    data={"state": "input_required", "task_id": task_id},')
    lines.append("                    final=True,")
    lines.append("                )")
    lines.append("                return")
    lines.append('            if event.get("event") == "on_chat_model_stream":')
    lines.append('                token = event["data"]["chunk"].content')
    lines.append("                if token:")
    lines.append("                    accumulated.append(token)")
    lines.append('                    yield A2AEvent(type="token", text=token)')
    lines.append('        response_text = "".join(accumulated)')
    lines.append('        _task_manager.update_task(task_id, "completed", response_text)')
    lines.append("        yield A2AEvent(")
    lines.append('            type="final",')
    lines.append("            text=response_text,")
    lines.append('            data={"state": "completed", "task_id": task_id},')
    lines.append("            final=True,")
    lines.append("        )")
    lines.append("    except Exception as exc:")
    lines.append('        _task_manager.update_task(task_id, "failed", str(exc))')
    lines.append("        raise")
    lines.append("")
    lines.append("")

    # --- A2AHandler instance (with opt-in idempotency cache) ---
    lines.append("from vystak.transport import A2AResult as _A2AResult")
    lines.append("from vystak.transport import IdempotencyCache as _IdempotencyCache")
    lines.append("import os as _idemp_os")
    lines.append("_idemp_ttl = float(_idemp_os.environ.get('VYSTAK_IDEMPOTENCY_TTL', '60'))")
    lines.append("_a2a_idempotency_cache = _IdempotencyCache[_A2AResult](ttl_seconds=_idemp_ttl)")
    lines.append("_a2a_handler = A2AHandler(")
    lines.append("    one_shot=_a2a_one_shot,")
    lines.append("    streaming=_a2a_streaming,")
    lines.append("    idempotency_cache=_a2a_idempotency_cache,")
    lines.append(")")
    lines.append("")
    lines.append("")

    # --- /a2a POST route (thin JSON-RPC <-> A2A adapter) ---
    lines.append('@app.post("/a2a")')
    lines.append("async def a2a_endpoint(request: Request):")
    lines.append('    """A2A JSON-RPC 2.0 endpoint — thin adapter over A2AHandler."""')
    lines.append("    body = await request.json()")
    lines.append('    method = body.get("method", "")')
    lines.append('    params = body.get("params", {})')
    lines.append('    req_id = body.get("id")')
    lines.append("")
    lines.append('    if method == "tasks/sendSubscribe":')
    lines.append("        return await _handle_tasks_send_subscribe(params, req_id)")
    lines.append("")
    lines.append('    if method == "tasks/send":')
    lines.append("        result = await _handle_tasks_send(params)")
    lines.append('        return {"jsonrpc": "2.0", "id": req_id, "result": result}')
    lines.append("")
    lines.append('    if method == "tasks/get":')
    lines.append("        result = await _handle_tasks_get(params)")
    lines.append('        return {"jsonrpc": "2.0", "id": req_id, "result": result}')
    lines.append("")
    lines.append('    if method == "tasks/cancel":')
    lines.append("        result = await _handle_tasks_cancel(params)")
    lines.append('        return {"jsonrpc": "2.0", "id": req_id, "result": result}')
    lines.append("")
    lines.append(
        '    return {"jsonrpc": "2.0", "id": req_id, "error": {"code": -32601, "message": "Method not found"}}'
    )
    lines.append("")
    lines.append("")

    # --- tasks/send adapter ---
    lines.append("async def _handle_tasks_send(params: dict) -> dict:")
    lines.append('    """Build A2AMessage, dispatch via A2AHandler, return final task dict."""')
    lines.append('    task_id = params.get("id") or str(uuid.uuid4())')
    lines.append('    raw_message = params.get("message", {})')
    lines.append('    metadata = params.get("metadata", {})')
    lines.append('    session_id = params.get("sessionId") or task_id')
    lines.append("")
    lines.append("    # Seed the task manager so resume scenarios work consistently with")
    lines.append("    # prior behaviour (task created before handler dispatch).")
    lines.append("    if _task_manager.get_task(task_id) is None:")
    lines.append("        _task_manager.create_task(task_id, raw_message)")
    lines.append("")
    lines.append("    a2a_message = A2AMessage(")
    lines.append('        role=raw_message.get("role", "user"),')
    lines.append('        parts=raw_message.get("parts", []),')
    lines.append("        correlation_id=task_id,")
    lines.append("        metadata=metadata,")
    lines.append("    )")
    lines.append("")
    lines.append("    # Propagate sessionId through metadata so the callable sees it.")
    lines.append('    dispatch_metadata = {**metadata, "sessionId": session_id}')
    lines.append("")
    lines.append("    try:")
    lines.append("        await _a2a_handler.dispatch(a2a_message, dispatch_metadata)")
    lines.append("    except Exception:")
    lines.append("        # _a2a_one_shot already recorded the 'failed' state before re-raising.")
    lines.append("        pass")
    lines.append("")
    lines.append("    # Return the final task dict (envelope shape preserved).")
    lines.append("    task = _task_manager.get_task(task_id)")
    lines.append("    if task is None:")
    lines.append('        return {"error": "Task not found", "id": task_id}')
    lines.append("    return task")
    lines.append("")
    lines.append("")

    # tasks/get handler (unchanged)
    lines.append("async def _handle_tasks_get(params: dict) -> dict:")
    lines.append('    """Handle tasks/get — return task by ID."""')
    lines.append('    task_id = params.get("id")')
    lines.append("    task = _task_manager.get_task(task_id)")
    lines.append("    if task is None:")
    lines.append('        return {"error": "Task not found", "id": task_id}')
    lines.append("    return task")
    lines.append("")
    lines.append("")

    # tasks/cancel handler (unchanged)
    lines.append("async def _handle_tasks_cancel(params: dict) -> dict:")
    lines.append('    """Handle tasks/cancel — cancel a task."""')
    lines.append('    task_id = params.get("id")')
    lines.append('    task = _task_manager.update_task(task_id, "canceled")')
    lines.append("    if task is None:")
    lines.append('        return {"error": "Task not found", "id": task_id}')
    lines.append("    return task")
    lines.append("")
    lines.append("")

    # tasks/sendSubscribe adapter — delegates to A2AHandler.dispatch_stream
    lines.append(
        "async def _handle_tasks_send_subscribe(params: dict, req_id) -> EventSourceResponse:"
    )
    lines.append('    """Handle tasks/sendSubscribe — stream agent response via SSE."""')
    lines.append('    task_id = params.get("id") or str(uuid.uuid4())')
    lines.append('    raw_message = params.get("message", {})')
    lines.append('    metadata = params.get("metadata", {})')
    lines.append('    session_id = params.get("sessionId") or task_id')
    lines.append("")
    lines.append("    if _task_manager.get_task(task_id) is None:")
    lines.append("        _task_manager.create_task(task_id, raw_message)")
    lines.append("")
    lines.append("    a2a_message = A2AMessage(")
    lines.append('        role=raw_message.get("role", "user"),')
    lines.append('        parts=raw_message.get("parts", []),')
    lines.append("        correlation_id=task_id,")
    lines.append("        metadata=metadata,")
    lines.append("    )")
    lines.append('    dispatch_metadata = {**metadata, "sessionId": session_id}')
    lines.append("")
    lines.append("    async def event_generator():")
    lines.append("        try:")
    lines.append(
        "            async for ev in _a2a_handler.dispatch_stream(a2a_message, dispatch_metadata):"
    )
    lines.append('                if ev.type == "token":')
    lines.append("                    chunk_event = {")
    lines.append('                        "jsonrpc": "2.0",')
    lines.append('                        "id": req_id,')
    lines.append('                        "result": {')
    lines.append('                            "id": task_id,')
    lines.append('                            "artifact": {')
    lines.append('                                "parts": [{"text": ev.text or ""}],')
    lines.append('                                "index": 0,')
    lines.append('                                "append": True,')
    lines.append("                            },")
    lines.append("                        },")
    lines.append("                    }")
    lines.append('                    yield {"data": json.dumps(chunk_event)}')
    lines.append('                elif ev.type == "status":')
    lines.append('                    state = (ev.data or {}).get("state", "input_required")')
    lines.append("                    status_event = {")
    lines.append('                        "jsonrpc": "2.0",')
    lines.append('                        "id": req_id,')
    lines.append('                        "result": {')
    lines.append('                            "id": task_id,')
    lines.append('                            "status": {')
    lines.append('                                "state": state,')
    lines.append(
        '                                "message": {"role": "agent", "parts": [{"text": ev.text or ""}]},'
    )
    lines.append("                            },")
    lines.append('                            "final": ev.final,')
    lines.append("                        },")
    lines.append("                    }")
    lines.append('                    yield {"data": json.dumps(status_event)}')
    lines.append("                    if ev.final:")
    lines.append("                        return")
    lines.append('                elif ev.type == "final":')
    lines.append("                    final_event = {")
    lines.append('                        "jsonrpc": "2.0",')
    lines.append('                        "id": req_id,')
    lines.append('                        "result": {')
    lines.append('                            "id": task_id,')
    lines.append('                            "status": {"state": "completed"},')
    lines.append('                            "final": True,')
    lines.append("                        },")
    lines.append("                    }")
    lines.append('                    yield {"data": json.dumps(final_event)}')
    lines.append("        except Exception as exc:")
    lines.append("            error_event = {")
    lines.append('                "jsonrpc": "2.0",')
    lines.append('                "id": req_id,')
    lines.append('                "error": {"code": -32603, "message": str(exc)},')
    lines.append("            }")
    lines.append('            yield {"data": json.dumps(error_event)}')
    lines.append("")
    lines.append("    return EventSourceResponse(event_generator())")
    lines.append("")

    return "\n".join(lines)
