"""A2A protocol code generation for LangChain/LangGraph agents."""

from vystak.schema.agent import Agent


def generate_agent_card_code(agent: Agent) -> str:
    """Generate AGENT_CARD dict constant and /.well-known/agent.json endpoint."""
    description = (
        (agent.instructions or agent.name)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    skills_list = [skill.name for skill in agent.skills]

    lines = []
    lines.append("# A2A Agent Card")
    lines.append("AGENT_CARD = {")
    lines.append(f'    "name": "{agent.name}",')
    lines.append(f'    "description": "{description}",')
    lines.append('    "url": "http://localhost:8000",')
    lines.append('    "version": "0.1.0",')
    lines.append('    "capabilities": {')
    lines.append('        "streaming": True,')
    lines.append('        "pushNotifications": False,')
    lines.append('        "stateTransitionHistory": False,')
    lines.append("    },")
    lines.append('    "skills": [')
    for skill_name in skills_list:
        lines.append("        {")
        lines.append(f'            "id": "{skill_name}",')
        lines.append(f'            "name": "{skill_name}",')
        lines.append("        },")
    lines.append("    ],")
    lines.append(f'    "models": ["vystak/{agent.name}"],')
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append('@app.get("/.well-known/agent.json")')
    lines.append("async def agent_card():")
    lines.append("    return AGENT_CARD")
    lines.append("")

    return "\n".join(lines)


def generate_task_manager_code() -> str:
    """Generate TaskManager class with in-memory task storage."""
    lines = []
    lines.append("# A2A Task Manager")
    lines.append("_task_manager = None")
    lines.append("")
    lines.append("")
    lines.append("class TaskManager:")
    lines.append('    """In-memory task manager for A2A protocol."""')
    lines.append(
        "    # Task states: submitted, working, input_required, completed, canceled, failed"
    )
    lines.append("")
    lines.append("    def __init__(self):")
    lines.append("        self._tasks = {}")
    lines.append("")
    lines.append("    def create_task(self, task_id: str, message: dict) -> dict:")
    lines.append('        """Create a new task with submitted state."""')
    lines.append("        task = {")
    lines.append('            "id": task_id,')
    lines.append('            "status": {')
    lines.append('                "state": "submitted",')
    lines.append("            },")
    lines.append('            "history": [message],')
    lines.append("        }")
    lines.append("        self._tasks[task_id] = task")
    lines.append("        return task")
    lines.append("")
    lines.append("    def get_task(self, task_id: str) -> dict | None:")
    lines.append('        """Get a task by ID."""')
    lines.append("        return self._tasks.get(task_id)")
    lines.append("")
    lines.append(
        "    def update_task(self, task_id: str, state: str, result: str | None = None) -> dict | None:"
    )
    lines.append('        """Update task state and optionally set result."""')
    lines.append("        task = self._tasks.get(task_id)")
    lines.append("        if task is None:")
    lines.append("            return None")
    lines.append('        task["status"]["state"] = state')
    lines.append("        if result is not None:")
    lines.append('            task["status"]["message"] = {')
    lines.append('                "role": "agent",')
    lines.append('                "parts": [{"text": result}],')
    lines.append("            }")
    lines.append("        return task")
    lines.append("")
    lines.append("")
    lines.append("_task_manager = TaskManager()")
    lines.append("")

    return "\n".join(lines)


def generate_a2a_handler_code(agent: Agent) -> str:
    """Generate the /a2a POST endpoint and JSON-RPC dispatcher."""
    lines = []

    # Import Command for resume
    lines.append("from langgraph.types import Command")
    lines.append("from fastapi import Request")
    lines.append("")
    lines.append("")

    # Main /a2a endpoint
    lines.append('@app.post("/a2a")')
    lines.append("async def a2a_endpoint(request: Request):")
    lines.append('    """A2A JSON-RPC 2.0 endpoint."""')
    lines.append("    body = await request.json()")
    lines.append('    method = body.get("method", "")')
    lines.append('    params = body.get("params", {})')
    lines.append('    req_id = body.get("id")')
    lines.append("")
    lines.append('    if method == "tasks/send":')
    lines.append("        result = await _handle_tasks_send(params)")
    lines.append('    elif method == "tasks/get":')
    lines.append("        result = await _handle_tasks_get(params)")
    lines.append('    elif method == "tasks/cancel":')
    lines.append("        result = await _handle_tasks_cancel(params)")
    lines.append('    elif method == "tasks/sendSubscribe":')
    lines.append("        return await _handle_tasks_send_subscribe(params, req_id)")
    lines.append("    else:")
    lines.append(
        '        return {"jsonrpc": "2.0", "id": req_id, "error": {"code": -32601, "message": "Method not found"}}'
    )
    lines.append("")
    lines.append('    return {"jsonrpc": "2.0", "id": req_id, "result": result}')
    lines.append("")
    lines.append("")

    # tasks/send handler
    lines.append("async def _handle_tasks_send(params: dict) -> dict:")
    lines.append('    """Handle tasks/send — invoke agent and return completed task."""')
    lines.append('    task_id = params.get("id") or str(uuid.uuid4())')
    lines.append('    message = params.get("message", {})')
    lines.append('    metadata = params.get("metadata", {})')
    lines.append('    session_id = params.get("sessionId") or task_id')
    lines.append("")
    lines.append("    # Extract context from metadata (propagated from caller agent)")
    lines.append('    trace_id = metadata.get("trace_id") or str(uuid.uuid4())')
    lines.append('    user_id = metadata.get("user_id")')
    lines.append('    project_id = metadata.get("project_id")')
    lines.append('    parent_task_id = metadata.get("parent_task_id")')
    lines.append("")
    lines.append("    task = _task_manager.create_task(task_id, message)")
    lines.append('    _task_manager.update_task(task_id, "working")')
    lines.append("")
    lines.append("    # Extract text from message parts")
    lines.append('    parts = message.get("parts", [])')
    lines.append('    text = " ".join(p.get("text", "") for p in parts if "text" in p)')
    lines.append("")
    lines.append("    # Build config with propagated context")
    lines.append('    config = {"configurable": {')
    lines.append('        "thread_id": session_id,')
    lines.append('        "trace_id": trace_id,')
    lines.append('        "user_id": user_id,')
    lines.append('        "project_id": project_id,')
    lines.append('        "parent_task_id": parent_task_id,')
    lines.append('        "agent_name": AGENT_NAME,')
    lines.append("    }}")
    lines.append("")
    lines.append("    # Check if task is in input_required state (resume scenario)")
    lines.append("    existing = _task_manager.get_task(task_id)")
    lines.append('    current_state = existing["status"]["state"] if existing else None')
    lines.append("")
    lines.append('    if current_state == "input_required":')
    lines.append("        agent_input = Command(resume=text)")
    lines.append("    else:")
    lines.append('        agent_input = {"messages": [("user", text)]}')
    lines.append("")
    lines.append("    try:")
    lines.append("        result = await _agent.ainvoke(")
    lines.append("            agent_input,")
    lines.append("            config=config,")
    lines.append("        )")
    lines.append("")
    lines.append("        # Check for interrupt / input_required")
    lines.append('        if "__interrupt__" in result:')
    lines.append('            interrupt_value = result["__interrupt__"]')
    lines.append(
        '            interrupt_text = str(interrupt_value[0].value) if interrupt_value else "Input required"'
    )
    lines.append(
        '            task = _task_manager.update_task(task_id, "input_required", interrupt_text)'
    )
    lines.append("        else:")
    lines.append('            content = result["messages"][-1].content')
    lines.append("            if isinstance(content, list):")
    lines.append('                response_text = "".join(')
    lines.append(
        '                    block.get("text", "") if isinstance(block, dict) else str(block)'
    )
    lines.append("                    for block in content")
    lines.append("                )")
    lines.append("            else:")
    lines.append("                response_text = str(content)")
    lines.append(
        '            task = _task_manager.update_task(task_id, "completed", response_text)'
    )
    lines.append("    except Exception as exc:")
    lines.append('        task = _task_manager.update_task(task_id, "failed", str(exc))')
    lines.append("")
    lines.append("    return task")
    lines.append("")
    lines.append("")

    # tasks/get handler
    lines.append("async def _handle_tasks_get(params: dict) -> dict:")
    lines.append('    """Handle tasks/get — return task by ID."""')
    lines.append('    task_id = params.get("id")')
    lines.append("    task = _task_manager.get_task(task_id)")
    lines.append("    if task is None:")
    lines.append('        return {"error": "Task not found", "id": task_id}')
    lines.append("    return task")
    lines.append("")
    lines.append("")

    # tasks/cancel handler
    lines.append("async def _handle_tasks_cancel(params: dict) -> dict:")
    lines.append('    """Handle tasks/cancel — cancel a task."""')
    lines.append('    task_id = params.get("id")')
    lines.append('    task = _task_manager.update_task(task_id, "canceled")')
    lines.append("    if task is None:")
    lines.append('        return {"error": "Task not found", "id": task_id}')
    lines.append("    return task")
    lines.append("")
    lines.append("")

    # tasks/sendSubscribe handler (SSE streaming)
    lines.append(
        "async def _handle_tasks_send_subscribe(params: dict, req_id) -> EventSourceResponse:"
    )
    lines.append('    """Handle tasks/sendSubscribe — stream agent response via SSE."""')
    lines.append('    task_id = params.get("id") or str(uuid.uuid4())')
    lines.append('    message = params.get("message", {})')
    lines.append('    metadata = params.get("metadata", {})')
    lines.append('    session_id = params.get("sessionId") or task_id')
    lines.append("")
    lines.append("    # Extract context from metadata")
    lines.append('    trace_id = metadata.get("trace_id") or str(uuid.uuid4())')
    lines.append('    user_id = metadata.get("user_id")')
    lines.append('    project_id = metadata.get("project_id")')
    lines.append('    parent_task_id = metadata.get("parent_task_id")')
    lines.append("")
    lines.append("    task = _task_manager.create_task(task_id, message)")
    lines.append('    _task_manager.update_task(task_id, "working")')
    lines.append("")
    lines.append("    # Extract text from message parts")
    lines.append('    parts = message.get("parts", [])')
    lines.append('    text = " ".join(p.get("text", "") for p in parts if "text" in p)')
    lines.append("")
    lines.append("    # Build config with propagated context")
    lines.append('    config = {"configurable": {')
    lines.append('        "thread_id": session_id,')
    lines.append('        "trace_id": trace_id,')
    lines.append('        "user_id": user_id,')
    lines.append('        "project_id": project_id,')
    lines.append('        "parent_task_id": parent_task_id,')
    lines.append('        "agent_name": AGENT_NAME,')
    lines.append("    }}")
    lines.append("")
    lines.append("    # Check if task is in input_required state (resume scenario)")
    lines.append("    existing = _task_manager.get_task(task_id)")
    lines.append('    current_state = existing["status"]["state"] if existing else None')
    lines.append("")
    lines.append('    if current_state == "input_required":')
    lines.append("        agent_input = Command(resume=text)")
    lines.append("    else:")
    lines.append('        agent_input = {"messages": [("user", text)]}')
    lines.append("")
    lines.append("    async def event_generator():")
    lines.append("        accumulated = []")
    lines.append("        try:")
    lines.append("            async for event in _agent.astream_events(")
    lines.append("                agent_input,")
    lines.append("                config=config,")
    lines.append('                version="v2",')
    lines.append("            ):")
    lines.append('                if "__interrupt__" in event:')
    lines.append('                    interrupt_value = event["__interrupt__"]')
    lines.append(
        '                    interrupt_text = str(interrupt_value[0].value) if interrupt_value else "Input required"'
    )
    lines.append(
        '                    _task_manager.update_task(task_id, "input_required", interrupt_text)'
    )
    lines.append("                    status_event = {")
    lines.append('                        "jsonrpc": "2.0",')
    lines.append('                        "id": req_id,')
    lines.append('                        "result": {')
    lines.append('                            "id": task_id,')
    lines.append(
        '                            "status": {"state": "input_required", "message": {"role": "agent", "parts": [{"text": interrupt_text}]}},'
    )
    lines.append('                            "final": True,')
    lines.append("                        },")
    lines.append("                    }")
    lines.append('                    yield {"data": json.dumps(status_event)}')
    lines.append("                    return")
    lines.append('                if event.get("event") == "on_chat_model_stream":')
    lines.append('                    token = event["data"]["chunk"].content')
    lines.append("                    if token:")
    lines.append("                        accumulated.append(token)")
    lines.append("                        chunk_event = {")
    lines.append('                            "jsonrpc": "2.0",')
    lines.append('                            "id": req_id,')
    lines.append('                            "result": {')
    lines.append('                                "id": task_id,')
    lines.append('                                "artifact": {')
    lines.append('                                    "parts": [{"text": token}],')
    lines.append('                                    "index": 0,')
    lines.append('                                    "append": True,')
    lines.append("                                },")
    lines.append("                            },")
    lines.append("                        }")
    lines.append('                        yield {"data": json.dumps(chunk_event)}')
    lines.append('            response_text = "".join(accumulated)')
    lines.append('            _task_manager.update_task(task_id, "completed", response_text)')
    lines.append("            final_event = {")
    lines.append('                "jsonrpc": "2.0",')
    lines.append('                "id": req_id,')
    lines.append('                "result": {')
    lines.append('                    "id": task_id,')
    lines.append('                    "status": {"state": "completed"},')
    lines.append('                    "final": True,')
    lines.append("                },")
    lines.append("            }")
    lines.append('            yield {"data": json.dumps(final_event)}')
    lines.append("        except Exception as exc:")
    lines.append('            _task_manager.update_task(task_id, "failed", str(exc))')
    lines.append("            error_event = {")
    lines.append('                "jsonrpc": "2.0",')
    lines.append('                "id": req_id,')
    lines.append('                "error": {"code": -32603, "message": str(exc)},')
    lines.append("            }")
    lines.append('            yield {"data": json.dumps(error_event)}')
    lines.append("")
    lines.append("    return EventSourceResponse(event_generator())")
    lines.append("")

    return "\n".join(lines)
