"""A2A protocol code generation for LangChain/LangGraph agents."""

from vystak.schema.agent import Agent


def generate_agent_card_code(agent: Agent) -> str:
    """Generate AGENT_CARD dict constant and /.well-known/agent.json endpoint."""
    description = (
        (agent.instructions or agent.name)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )
    skills_list = [skill.name for skill in agent.skills]

    lines = []
    lines.append("# A2A Agent Card")
    lines.append("AGENT_CARD = {")
    lines.append(f'    "name": "{agent.name}",')
    lines.append(f'    "description": "{description}",')
    lines.append('    "url": "http://localhost:8000",')
    lines.append('    "version": "0.1.0",')
    lines.append('    "capabilities": {')
    lines.append('        "streaming": True,')
    lines.append('        "pushNotifications": False,')
    lines.append('        "stateTransitionHistory": False,')
    lines.append("    },")
    lines.append('    "skills": [')
    for skill_name in skills_list:
        lines.append("        {")
        lines.append(f'            "id": "{skill_name}",')
        lines.append(f'            "name": "{skill_name}",')
        lines.append("        },")
    lines.append("    ],")
    lines.append(f'    "models": ["vystak/{agent.name}"],')
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append('@app.get("/.well-known/agent.json")')
    lines.append("async def agent_card():")
    lines.append("    return AGENT_CARD")
    lines.append("")

    return "\n".join(lines)


def generate_task_manager_code() -> str:
    """Generate TaskManager class with in-memory task storage."""
    lines = []
    lines.append("# A2A Task Manager")
    lines.append("_task_manager = None")
    lines.append("")
    lines.append("")
    lines.append("class TaskManager:")
    lines.append('    """In-memory task manager for A2A protocol."""')
    lines.append(
        "    # Task states: submitted, working, input_required, completed, canceled, failed"
    )
    lines.append("")
    lines.append("    def __init__(self):")
    lines.append("        self._tasks = {}")
    lines.append("")
    lines.append("    def create_task(self, task_id: str, message: dict) -> dict:")
    lines.append('        """Create a new task with submitted state."""')
    lines.append("        task = {")
    lines.append('            "id": task_id,')
    lines.append('            "status": {')
    lines.append('                "state": "submitted",')
    lines.append("            },")
    lines.append('            "history": [message],')
    lines.append("        }")
    lines.append("        self._tasks[task_id] = task")
    lines.append("        return task")
    lines.append("")
    lines.append("    def get_task(self, task_id: str) -> dict | None:")
    lines.append('        """Get a task by ID."""')
    lines.append("        return self._tasks.get(task_id)")
    lines.append("")
    lines.append(
        "    def update_task(self, task_id: str, state: str, result: str | None = None) -> dict | None:"
    )
    lines.append('        """Update task state and optionally set result."""')
    lines.append("        task = self._tasks.get(task_id)")
    lines.append("        if task is None:")
    lines.append("            return None")
    lines.append('        task["status"]["state"] = state')
    lines.append("        if result is not None:")
    lines.append('            task["status"]["message"] = {')
    lines.append('                "role": "agent",')
    lines.append('                "parts": [{"text": result}],')
    lines.append("            }")
    lines.append("        return task")
    lines.append("")
    lines.append("")
    lines.append("_task_manager = TaskManager()")
    lines.append("")

    return "\n".join(lines)


def generate_a2a_handler_code(agent: Agent) -> str:
    """Generate the /a2a POST endpoint and JSON-RPC dispatcher.

    Emits source that constructs a ``vystak.transport.A2AHandler`` from two
    local callables (``_a2a_one_shot`` and ``_a2a_streaming``) and dispatches
    through it from the FastAPI ``/a2a`` route. No behavioural change — same
    JSON-RPC envelope, same SSE events. Setting up for non-HTTP transports
    to re-use the handler via their listener implementations.
    """
    lines = []

    # Imports
    lines.append("from fastapi import Request")
    lines.append("from vystak.transport import A2AEvent, A2AHandler, A2AMessage, A2AResult")
    lines.append("")
    lines.append("")

    # --- One-shot callable (delegates to process_turn) ---
    lines.append("async def _a2a_one_shot(message: A2AMessage, metadata: dict) -> str:")
    lines.append('    """Invoke the agent one-shot via the shared turn core.')
    lines.append("")
    lines.append("    Wire-shape translator only:")
    lines.append("      A2A request envelope  ->  process_turn(text, metadata)")
    lines.append("      TurnResult            ->  A2A response text + _task_manager state")
    lines.append('    """')
    lines.append("    task_id = message.correlation_id or str(uuid.uuid4())")
    lines.append('    text = " ".join(p.get("text", "") for p in message.parts if "text" in p)')
    lines.append("")
    lines.append("    existing = _task_manager.get_task(task_id)")
    lines.append("    if existing is None:")
    lines.append("        _task_manager.create_task(task_id, {")
    lines.append('            "role": message.role,')
    lines.append('            "parts": message.parts,')
    lines.append("        })")
    lines.append('    _task_manager.update_task(task_id, "working")')
    lines.append("")
    lines.append("    # Resume scenario: pass current message as the resume payload")
    lines.append("    # rather than as a fresh user turn.")
    lines.append("    existing = _task_manager.get_task(task_id)")
    lines.append('    is_resume = existing is not None and existing["status"]["state"] == "input_required"')
    lines.append("    resume_text = text if is_resume else None")
    lines.append("    turn_text = '' if is_resume else text")
    lines.append("")
    lines.append("    try:")
    lines.append("        result = await process_turn(")
    lines.append("            turn_text, metadata,")
    lines.append("            resume_text=resume_text, task_id=task_id,")
    lines.append("        )")
    lines.append("    except Exception as exc:")
    lines.append('        _task_manager.update_task(task_id, "failed", str(exc))')
    lines.append("        raise")
    lines.append("")
    lines.append("    if result.interrupt_text is not None:")
    lines.append('        _task_manager.update_task(task_id, "input_required", result.interrupt_text)')
    lines.append("    else:")
    lines.append('        _task_manager.update_task(task_id, "completed", result.response_text)')
    lines.append("    return result.response_text")
    lines.append("")
    lines.append("")

    # --- Streaming callable (delegates to process_turn_streaming) ---
    lines.append("async def _a2a_streaming(message: A2AMessage, metadata: dict):")
    lines.append('    """Stream agent events via the shared streaming core.')
    lines.append("")
    lines.append("    Wire-shape translator: each TurnEvent becomes one A2AEvent.")
    lines.append('    """')
    lines.append("    task_id = message.correlation_id or str(uuid.uuid4())")
    lines.append('    text = " ".join(p.get("text", "") for p in message.parts if "text" in p)')
    lines.append("")
    lines.append("    existing = _task_manager.get_task(task_id)")
    lines.append("    if existing is None:")
    lines.append("        _task_manager.create_task(task_id, {")
    lines.append('            "role": message.role,')
    lines.append('            "parts": message.parts,')
    lines.append("        })")
    lines.append('    _task_manager.update_task(task_id, "working")')
    lines.append("")
    lines.append("    existing = _task_manager.get_task(task_id)")
    lines.append('    is_resume = existing is not None and existing["status"]["state"] == "input_required"')
    lines.append("    resume_text = text if is_resume else None")
    lines.append("    turn_text = '' if is_resume else text")
    lines.append("")
    lines.append("    try:")
    lines.append("        async for ev in process_turn_streaming(")
    lines.append("            turn_text, metadata,")
    lines.append("            resume_text=resume_text, task_id=task_id,")
    lines.append("        ):")
    lines.append('            if ev.type == "token":')
    lines.append('                yield A2AEvent(type="token", text=ev.text)')
    lines.append('            elif ev.type == "tool_call_start":')
    lines.append('                yield A2AEvent(type="tool_call", data=ev.data)')
    lines.append('            elif ev.type == "tool_call_end":')
    lines.append('                yield A2AEvent(type="tool_result", data=ev.data)')
    lines.append('            elif ev.type == "interrupt":')
    lines.append('                _task_manager.update_task(task_id, "input_required", ev.text)')
    lines.append("                yield A2AEvent(")
    lines.append('                    type="status",')
    lines.append("                    text=ev.text,")
    lines.append('                    data={"state": "input_required", "task_id": task_id},')
    lines.append("                    final=True,")
    lines.append("                )")
    lines.append("                return")
    lines.append('            elif ev.type == "final":')
    lines.append('                _task_manager.update_task(task_id, "completed", ev.text)')
    lines.append("                yield A2AEvent(")
    lines.append('                    type="final",')
    lines.append("                    text=ev.text,")
    lines.append('                    data={"state": "completed", "task_id": task_id},')
    lines.append("                    final=True,")
    lines.append("                )")
    lines.append("    except Exception as exc:")
    lines.append('        _task_manager.update_task(task_id, "failed", str(exc))')
    lines.append("        raise")
    lines.append("")
    lines.append("")

    # --- A2AHandler instance (with opt-in idempotency cache) ---
    lines.append("from vystak.transport import A2AResult as _A2AResult")
    lines.append("from vystak.transport import IdempotencyCache as _IdempotencyCache")
    lines.append("import os as _idemp_os")
    lines.append("_idemp_ttl = float(_idemp_os.environ.get('VYSTAK_IDEMPOTENCY_TTL', '60'))")
    lines.append("_a2a_idempotency_cache = _IdempotencyCache[_A2AResult](ttl_seconds=_idemp_ttl)")
    lines.append("_a2a_handler = A2AHandler(")
    lines.append("    one_shot=_a2a_one_shot,")
    lines.append("    streaming=_a2a_streaming,")
    lines.append("    idempotency_cache=_a2a_idempotency_cache,")
    lines.append(")")
    lines.append("")
    lines.append("")

    # --- /a2a POST route (thin JSON-RPC <-> A2A adapter) ---
    lines.append('@app.post("/a2a")')
    lines.append("async def a2a_endpoint(request: Request):")
    lines.append('    """A2A JSON-RPC 2.0 endpoint — thin adapter over A2AHandler."""')
    lines.append("    body = await request.json()")
    lines.append('    method = body.get("method", "")')
    lines.append('    params = body.get("params", {})')
    lines.append('    req_id = body.get("id")')
    lines.append("")
    lines.append('    if method == "tasks/sendSubscribe":')
    lines.append("        return await _handle_tasks_send_subscribe(params, req_id)")
    lines.append("")
    lines.append('    if method == "tasks/send":')
    lines.append("        result = await _handle_tasks_send(params)")
    lines.append('        return {"jsonrpc": "2.0", "id": req_id, "result": result}')
    lines.append("")
    lines.append('    if method == "tasks/get":')
    lines.append("        result = await _handle_tasks_get(params)")
    lines.append('        return {"jsonrpc": "2.0", "id": req_id, "result": result}')
    lines.append("")
    lines.append('    if method == "tasks/cancel":')
    lines.append("        result = await _handle_tasks_cancel(params)")
    lines.append('        return {"jsonrpc": "2.0", "id": req_id, "result": result}')
    lines.append("")
    lines.append(
        '    return {"jsonrpc": "2.0", "id": req_id, "error": {"code": -32601, "message": "Method not found"}}'
    )
    lines.append("")
    lines.append("")

    # --- tasks/send adapter ---
    lines.append("async def _handle_tasks_send(params: dict) -> dict:")
    lines.append('    """Build A2AMessage, dispatch via A2AHandler, return final task dict."""')
    lines.append('    task_id = params.get("id") or str(uuid.uuid4())')
    lines.append('    raw_message = params.get("message", {})')
    lines.append('    metadata = params.get("metadata", {})')
    # Wire format puts sessionId inside params["metadata"]; keep params["sessionId"]
    # as a top-level fallback. Only fall through to task_id if neither is set.
    lines.append('    session_id = metadata.get("sessionId") or params.get("sessionId") or task_id')
    lines.append("")
    lines.append("    # Seed the task manager so resume scenarios work consistently with")
    lines.append("    # prior behaviour (task created before handler dispatch).")
    lines.append("    if _task_manager.get_task(task_id) is None:")
    lines.append("        _task_manager.create_task(task_id, raw_message)")
    lines.append("")
    lines.append("    a2a_message = A2AMessage(")
    lines.append('        role=raw_message.get("role", "user"),')
    lines.append('        parts=raw_message.get("parts", []),')
    lines.append("        correlation_id=task_id,")
    lines.append("        metadata=metadata,")
    lines.append("    )")
    lines.append("")
    lines.append("    # Propagate sessionId through metadata so the callable sees it.")
    lines.append('    dispatch_metadata = {**metadata, "sessionId": session_id}')
    lines.append("")
    lines.append("    try:")
    lines.append("        result = await _a2a_handler.dispatch(a2a_message, dispatch_metadata)")
    lines.append("        # Idempotency cache hit path: dispatch short-circuited, so")
    lines.append("        # _a2a_one_shot never ran and never updated _task_manager.")
    lines.append("        # Apply the cached A2AResult to the freshly-seeded task now.")
    lines.append("        existing = _task_manager.get_task(task_id)")
    lines.append("        state = (existing or {}).get('status', {}).get('state')")
    lines.append("        if state in (None, 'submitted'):")
    lines.append("            _task_manager.update_task(task_id, 'completed', result.text)")
    lines.append("    except Exception:")
    lines.append("        # _a2a_one_shot already recorded the 'failed' state before re-raising.")
    lines.append("        pass")
    lines.append("")
    lines.append("    # Return the final task dict (envelope shape preserved).")
    lines.append("    task = _task_manager.get_task(task_id)")
    lines.append("    if task is None:")
    lines.append('        return {"error": "Task not found", "id": task_id}')
    lines.append("    return task")
    lines.append("")
    lines.append("")

    # tasks/get handler (unchanged)
    lines.append("async def _handle_tasks_get(params: dict) -> dict:")
    lines.append('    """Handle tasks/get — return task by ID."""')
    lines.append('    task_id = params.get("id")')
    lines.append("    task = _task_manager.get_task(task_id)")
    lines.append("    if task is None:")
    lines.append('        return {"error": "Task not found", "id": task_id}')
    lines.append("    return task")
    lines.append("")
    lines.append("")

    # tasks/cancel handler (unchanged)
    lines.append("async def _handle_tasks_cancel(params: dict) -> dict:")
    lines.append('    """Handle tasks/cancel — cancel a task."""')
    lines.append('    task_id = params.get("id")')
    lines.append('    task = _task_manager.update_task(task_id, "canceled")')
    lines.append("    if task is None:")
    lines.append('        return {"error": "Task not found", "id": task_id}')
    lines.append("    return task")
    lines.append("")
    lines.append("")

    # tasks/sendSubscribe adapter — delegates to A2AHandler.dispatch_stream
    lines.append(
        "async def _handle_tasks_send_subscribe(params: dict, req_id) -> EventSourceResponse:"
    )
    lines.append('    """Handle tasks/sendSubscribe — stream agent response via SSE."""')
    lines.append('    task_id = params.get("id") or str(uuid.uuid4())')
    lines.append('    raw_message = params.get("message", {})')
    lines.append('    metadata = params.get("metadata", {})')
    # Wire format puts sessionId inside params["metadata"]; keep params["sessionId"]
    # as a top-level fallback. Only fall through to task_id if neither is set.
    lines.append('    session_id = metadata.get("sessionId") or params.get("sessionId") or task_id')
    lines.append("")
    lines.append("    if _task_manager.get_task(task_id) is None:")
    lines.append("        _task_manager.create_task(task_id, raw_message)")
    lines.append("")
    lines.append("    a2a_message = A2AMessage(")
    lines.append('        role=raw_message.get("role", "user"),')
    lines.append('        parts=raw_message.get("parts", []),')
    lines.append("        correlation_id=task_id,")
    lines.append("        metadata=metadata,")
    lines.append("    )")
    lines.append('    dispatch_metadata = {**metadata, "sessionId": session_id}')
    lines.append("")
    lines.append("    async def event_generator():")
    lines.append("        try:")
    lines.append(
        "            async for ev in _a2a_handler.dispatch_stream(a2a_message, dispatch_metadata):"
    )
    lines.append('                if ev.type == "token":')
    lines.append("                    chunk_event = {")
    lines.append('                        "jsonrpc": "2.0",')
    lines.append('                        "id": req_id,')
    lines.append('                        "result": {')
    lines.append('                            "id": task_id,')
    lines.append('                            "artifact": {')
    lines.append('                                "parts": [{"text": ev.text or ""}],')
    lines.append('                                "index": 0,')
    lines.append('                                "append": True,')
    lines.append("                            },")
    lines.append("                        },")
    lines.append("                    }")
    lines.append('                    yield {"data": json.dumps(chunk_event)}')
    lines.append('                elif ev.type == "status":')
    lines.append('                    state = (ev.data or {}).get("state", "input_required")')
    lines.append("                    status_event = {")
    lines.append('                        "jsonrpc": "2.0",')
    lines.append('                        "id": req_id,')
    lines.append('                        "result": {')
    lines.append('                            "id": task_id,')
    lines.append('                            "status": {')
    lines.append('                                "state": state,')
    lines.append(
        '                                "message": {"role": "agent", "parts": [{"text": ev.text or ""}]},'
    )
    lines.append("                            },")
    lines.append('                            "final": ev.final,')
    lines.append("                        },")
    lines.append("                    }")
    lines.append('                    yield {"data": json.dumps(status_event)}')
    lines.append("                    if ev.final:")
    lines.append("                        return")
    lines.append('                elif ev.type == "tool_call":')
    lines.append('                    yield {"data": ev.model_dump_json()}')
    lines.append('                elif ev.type == "tool_result":')
    lines.append('                    yield {"data": ev.model_dump_json()}')
    lines.append('                elif ev.type == "final":')
    lines.append("                    final_event = {")
    lines.append('                        "jsonrpc": "2.0",')
    lines.append('                        "id": req_id,')
    lines.append('                        "result": {')
    lines.append('                            "id": task_id,')
    lines.append('                            "status": {"state": "completed"},')
    lines.append('                            "final": True,')
    lines.append("                        },")
    lines.append("                    }")
    lines.append('                    yield {"data": json.dumps(final_event)}')
    lines.append('                    yield {"data": ev.model_dump_json()}')
    lines.append("        except Exception as exc:")
    lines.append("            error_event = {")
    lines.append('                "jsonrpc": "2.0",')
    lines.append('                "id": req_id,')
    lines.append('                "error": {"code": -32603, "message": str(exc)},')
    lines.append("            }")
    lines.append('            yield {"data": json.dumps(error_event)}')
    lines.append("")
    lines.append("    return EventSourceResponse(event_generator())")
    lines.append("")

    return "\n".join(lines)
