"""Code generation for the ResponsesHandler class embedded in generated servers.

The generated ``ResponsesHandler`` owns the OpenAI Responses API semantics
(create / create_stream / get) in a form that is independent of the HTTP
transport. The FastAPI ``/v1/responses`` routes are reduced to thin adapters
that delegate into this handler; Task 4b will plug the same handler into the
non-HTTP transport listener via ``ServerDispatcher``.

Wire format (SSE event shapes, ``response.*`` event types, error envelopes)
is preserved exactly — this is a mechanical extraction.
"""

from vystak.schema.agent import Agent


def _uses_persistent_store(agent: Agent) -> bool:
    """Whether the agent uses a persistent (postgres/sqlite) session store.

    Delegates to ``templates._get_session_store`` via a lazy import so we
    match the canonical lookup logic exactly without creating an import
    cycle (``templates`` imports from this module).
    """
    from vystak_adapter_langchain.templates import _get_session_store

    session_store = _get_session_store(agent)
    return bool(session_store and session_store.engine in ("postgres", "sqlite"))


def generate_responses_handler_code(agent: Agent) -> str:
    """Emit the ``ResponsesHandler`` class as a Python source string.

    The generated class has three coroutine methods:

      * ``create(body, metadata)`` — non-streaming (sync or background) path.
        Returns a ``ResponseObject.model_dump()`` dict.
      * ``create_stream(body, metadata)`` — async-iterator of SSE chunks (each
        a plain dict; the caller is responsible for ``json.dumps`` + ``data:``
        framing).
      * ``get(response_id)`` — returns the stored response dict or ``None``.

    The class accesses LangGraph's compiled graph via ``self._graph`` and the
    in-memory response map via ``self._response_store``. Memory-action hooks
    (``handle_memory_actions`` + ``_store``) are looked up at the module level
    — they're only emitted when the agent uses a persistent session store.

    Errors that the previous inline routes signalled via HTTP status codes
    (404 for unknown ``previous_response_id``, 400 for chaining off an
    unstored response) are raised as ``fastapi.HTTPException`` from the
    handler. The route adapter reraises; a non-HTTP listener (Task 4b) can
    catch and translate to its own error envelope.
    """
    # ``agent_ref`` is always ``_agent`` in the current template (all four
    # shapes — persistent / mcp combinations — assign to ``_agent``), so we
    # can emit it as a plain literal and keep this module free of the
    # branching logic in ``templates.generate_server_py``.
    uses_persistent = _uses_persistent_store(agent)

    lines: list[str] = []

    lines.append("# === ResponsesHandler ===")
    lines.append("from fastapi import HTTPException as _ResponsesHTTPException")
    lines.append("")
    lines.append("")
    lines.append("class ResponsesHandler:")
    lines.append('    """Dispatches OpenAI Responses API calls to the agent\'s LangGraph.')
    lines.append("")
    lines.append("    Shared by the FastAPI ``/v1/responses`` routes and (in Task 4b) by the")
    lines.append("    transport listener for non-HTTP transports. Wire format is preserved:")
    lines.append("    the streaming path yields the exact same ``response.*`` event dicts as")
    lines.append("    the previous inline handler.")
    lines.append('    """')
    lines.append("")
    lines.append("    def __init__(self, graph, response_store):")
    lines.append("        self._graph = graph")
    lines.append("        self._response_store = response_store")
    lines.append("")

    # --- create (sync + background) ---------------------------------------
    lines.append("    async def create(self, body: dict, metadata: dict | None = None) -> dict:")
    lines.append('        """Handle a non-streaming /v1/responses create call.')
    lines.append("")
    lines.append("        ``body`` is the ``CreateResponseRequest.model_dump()`` dict. Returns")
    lines.append("        the ``ResponseObject.model_dump()`` dict (or an in-progress stub if")
    lines.append("        ``body['background']`` is true). Raises ``HTTPException`` for the")
    lines.append("        previously inline 404 / 400 error paths.")
    lines.append('        """')
    lines.append("        user_id = body.get('user_id')")
    lines.append("        project_id = body.get('project_id')")
    lines.append("        store = body.get('store', True)")
    lines.append("        previous_id = body.get('previous_response_id')")
    lines.append("")
    lines.append("        # Parse input into messages")
    lines.append("        input_messages = []")
    if uses_persistent:
        lines.append("        last_user_msg = ''")
    lines.append("        raw_input = body.get('input')")
    lines.append("        if isinstance(raw_input, str):")
    lines.append("            input_messages.append(('user', raw_input))")
    if uses_persistent:
        lines.append("            last_user_msg = raw_input")
    lines.append("        elif raw_input is not None:")
    lines.append("            for item in raw_input:")
    lines.append("                if isinstance(item, dict):")
    lines.append(
        "                    input_messages.append((item.get('role', 'user'), item.get('content', '')))"
    )
    if uses_persistent:
        lines.append("                    if item.get('role') == 'user' and item.get('content'):")
        lines.append("                        last_user_msg = item['content']")
    lines.append("                elif hasattr(item, 'role'):")
    lines.append("                    input_messages.append((item.role, item.content or ''))")
    if uses_persistent:
        lines.append("                    if item.role == 'user' and item.content:")
        lines.append("                        last_user_msg = item.content")
    lines.append("")
    lines.append("        # Determine thread_id and response_id")
    lines.append("        if previous_id:")
    lines.append("            if previous_id not in self._response_store:")
    lines.append("                raise _ResponsesHTTPException(")
    lines.append("                    status_code=404,")
    lines.append("                    detail=ErrorResponse(error=ErrorDetail(")
    lines.append("                        message=f\"Response '{previous_id}' not found\",")
    lines.append('                        type="invalid_request_error", code="response_not_found",')
    lines.append("                    )).model_dump(),")
    lines.append("                )")
    lines.append("            prev = self._response_store[previous_id]")
    lines.append("            if not prev.get('stored'):")
    lines.append("                raise _ResponsesHTTPException(")
    lines.append("                    status_code=400,")
    lines.append("                    detail=ErrorResponse(error=ErrorDetail(")
    lines.append(
        '                        message="Cannot chain from a response created with store=false",'
    )
    lines.append('                        type="invalid_request_error", code="invalid_value",')
    lines.append("                    )).model_dump(),")
    lines.append("                )")
    lines.append("            thread_id = prev.get('thread_id', str(uuid.uuid4()))")
    lines.append("            last_input_tokens = prev.get('last_input_tokens')")
    lines.append("            response_id = f'resp-{uuid.uuid4().hex[:16]}'")
    lines.append("        elif store:")
    lines.append("            response_id = f'resp-{uuid.uuid4().hex[:16]}'")
    lines.append("            thread_id = response_id")
    lines.append("            last_input_tokens = None")
    lines.append("        else:")
    lines.append("            response_id = f'resp-{uuid.uuid4().hex[:16]}'")
    lines.append("            thread_id = str(uuid.uuid4())")
    lines.append("            last_input_tokens = None")
    lines.append("")
    lines.append('        config = {"configurable": {')
    lines.append('            "thread_id": thread_id,')
    lines.append('            "user_id": user_id,')
    lines.append('            "project_id": project_id,')
    lines.append('            "agent_name": AGENT_NAME,')
    lines.append('            "last_input_tokens": last_input_tokens,')
    lines.append("        }}")
    lines.append("")
    # Background branch
    lines.append("        if body.get('background'):")
    lines.append("            self._response_store[response_id] = {")
    lines.append("                'id': response_id,")
    lines.append("                'status': 'in_progress',")
    lines.append("                'output': [],")
    lines.append("                'model': MODEL_ID,")
    lines.append("                'stored': store,")
    lines.append("                'thread_id': thread_id,")
    lines.append("                'created_at': int(time.time()),")
    lines.append("            }")
    lines.append("            asyncio.create_task(")
    lines.append(
        "                self._run_background(input_messages, config, response_id, user_id, project_id)"
    )
    lines.append("            )")
    lines.append("            return ResponseObject(")
    lines.append("                id=response_id,")
    lines.append('                status="in_progress",')
    lines.append("                output=[],")
    lines.append("                model=MODEL_ID,")
    lines.append("                created_at=int(time.time()),")
    lines.append("            ).model_dump()")
    lines.append("")
    # Synchronous invoke (delegates to shared one-shot core)
    lines.append("        metadata = {")
    lines.append('            "sessionId": thread_id,')
    lines.append('            "user_id": user_id,')
    lines.append('            "project_id": project_id,')
    lines.append("        }")
    lines.append("        turn = await process_turn('', metadata, messages=input_messages)")
    lines.append("        response_text = turn.response_text")
    lines.append("        # TODO: surface usage_metadata via TurnResult — currently zero.")
    lines.append("        usage_obj = None")
    lines.append("")
    lines.append(
        "        output = [ResponseOutput(type='message', role='assistant', content=response_text)]"
    )
    lines.append("        resp = ResponseObject(")
    lines.append("            id=response_id,")
    lines.append('            status="completed",')
    lines.append("            output=output,")
    lines.append("            model=MODEL_ID,")
    lines.append("            usage=usage_obj,")
    lines.append("            created_at=int(time.time()),")
    lines.append("        )")
    lines.append("        if store:")
    lines.append("            self._response_store[response_id] = {")
    lines.append("                'id': response_id,")
    lines.append("                'status': 'completed',")
    lines.append("                'output': output,")
    lines.append("                'model': MODEL_ID,")
    lines.append("                'usage': usage_obj,")
    lines.append("                'stored': True,")
    lines.append("                'thread_id': thread_id,")
    lines.append("                'last_input_tokens': usage_obj.input_tokens if usage_obj else None,")
    lines.append("                'created_at': int(time.time()),")
    lines.append("                'response': resp.model_dump(),")
    lines.append("            }")
    lines.append("        return resp.model_dump()")
    lines.append("")

    # --- _run_background --------------------------------------------------
    lines.append("    async def _run_background(")
    lines.append("        self, input_messages, config, response_id, user_id, project_id")
    lines.append("    ):")
    lines.append('        """Background execution path — mutates response_store in place."""')
    lines.append("        try:")
    lines.append("            # Sync background invoke (delegates to shared one-shot core)")
    lines.append("            metadata = {")
    lines.append('                "sessionId": config["configurable"].get("thread_id"),')
    lines.append('                "user_id": user_id,')
    lines.append('                "project_id": project_id,')
    lines.append("            }")
    lines.append("            turn = await process_turn(")
    lines.append("                '', metadata,")
    lines.append("                messages=input_messages, task_id=response_id,")
    lines.append("            )")
    lines.append("            response_text = turn.response_text")
    lines.append("            # TODO: surface usage_metadata via TurnResult — currently zero.")
    lines.append("            usage_obj = None")
    lines.append(
        "            output = [ResponseOutput(type='message', role='assistant', content=response_text)]"
    )
    lines.append("            self._response_store[response_id].update({")
    lines.append("                'status': 'completed',")
    lines.append("                'output': output,")
    lines.append("                'usage': usage_obj,")
    lines.append("            })")
    lines.append("        except Exception as exc:")
    lines.append("            self._response_store[response_id].update({")
    lines.append("                'status': 'failed',")
    lines.append("                'error': str(exc),")
    lines.append("            })")
    lines.append("")

    # --- get --------------------------------------------------------------
    lines.append("    async def get(self, response_id: str) -> dict | None:")
    lines.append('        """Return stored response dict for ``response_id`` or ``None``."""')
    lines.append("        if response_id not in self._response_store:")
    lines.append("            return None")
    lines.append("        stored = self._response_store[response_id]")
    lines.append("        if 'response' in stored:")
    lines.append("            result = dict(stored['response'])")
    lines.append("            result['thread_id'] = stored.get('thread_id')")
    lines.append("            return result")
    lines.append("        result = ResponseObject(")
    lines.append("            id=stored['id'],")
    lines.append("            status=stored['status'],")
    lines.append("            output=stored.get('output', []),")
    lines.append("            model=stored.get('model', MODEL_ID),")
    lines.append("            usage=stored.get('usage'),")
    lines.append("            created_at=stored.get('created_at', 0),")
    lines.append("        ).model_dump()")
    lines.append("        result['thread_id'] = stored.get('thread_id')")
    lines.append("        return result")
    lines.append("")

    # --- create_stream ----------------------------------------------------
    lines.append("    async def create_stream(self, body: dict, metadata: dict | None = None):")
    lines.append('        """Async-iterator over Responses API SSE event dicts.')
    lines.append("")
    lines.append("        Each yielded value is the chunk payload (already-structured dict or")
    lines.append('        the sentinel string ``"[DONE]"``). The caller frames it for the')
    lines.append("        wire (``EventSourceResponse`` wraps with ``data: json.dumps(chunk)``).")
    lines.append('        """')
    lines.append("        user_id = body.get('user_id')")
    lines.append("        project_id = body.get('project_id')")
    lines.append("        store = body.get('store', True)")
    lines.append("        previous_id = body.get('previous_response_id')")
    lines.append("")
    lines.append("        # Parse input into messages")
    lines.append("        input_messages = []")
    lines.append("        raw_input = body.get('input')")
    lines.append("        if isinstance(raw_input, str):")
    lines.append("            input_messages.append(('user', raw_input))")
    lines.append("        elif raw_input is not None:")
    lines.append("            for item in raw_input:")
    lines.append("                if isinstance(item, dict):")
    lines.append(
        "                    input_messages.append((item.get('role', 'user'), item.get('content', '')))"
    )
    lines.append("                elif hasattr(item, 'role'):")
    lines.append("                    input_messages.append((item.role, item.content or ''))")
    lines.append("")
    lines.append("        # Determine thread_id and response_id")
    lines.append("        if previous_id:")
    lines.append("            if previous_id not in self._response_store:")
    lines.append("                raise _ResponsesHTTPException(")
    lines.append("                    status_code=404,")
    lines.append("                    detail=ErrorResponse(error=ErrorDetail(")
    lines.append("                        message=f\"Response '{previous_id}' not found\",")
    lines.append('                        type="invalid_request_error", code="response_not_found",')
    lines.append("                    )).model_dump(),")
    lines.append("                )")
    lines.append("            prev = self._response_store[previous_id]")
    lines.append("            if not prev.get('stored'):")
    lines.append("                raise _ResponsesHTTPException(")
    lines.append("                    status_code=400,")
    lines.append("                    detail=ErrorResponse(error=ErrorDetail(")
    lines.append(
        '                        message="Cannot chain from a response created with store=false",'
    )
    lines.append('                        type="invalid_request_error", code="invalid_value",')
    lines.append("                    )).model_dump(),")
    lines.append("                )")
    lines.append("            thread_id = prev.get('thread_id', str(uuid.uuid4()))")
    lines.append("            last_input_tokens = prev.get('last_input_tokens')")
    lines.append("            response_id = f'resp-{uuid.uuid4().hex[:16]}'")
    lines.append("        elif store:")
    lines.append("            response_id = f'resp-{uuid.uuid4().hex[:16]}'")
    lines.append("            thread_id = response_id")
    lines.append("            last_input_tokens = None")
    lines.append("        else:")
    lines.append("            response_id = f'resp-{uuid.uuid4().hex[:16]}'")
    lines.append("            thread_id = str(uuid.uuid4())")
    lines.append("            last_input_tokens = None")
    lines.append("")
    lines.append('        config = {"configurable": {')
    lines.append('            "thread_id": thread_id,')
    lines.append('            "user_id": user_id,')
    lines.append('            "project_id": project_id,')
    lines.append('            "agent_name": AGENT_NAME,')
    lines.append('            "last_input_tokens": last_input_tokens,')
    lines.append("        }}")
    lines.append("")
    # Begin streaming body (previously _stream_response inner event_generator)
    lines.append("        created_at = int(time.time())")
    lines.append("        # response.created")
    lines.append("        yield {")
    lines.append('            "type": "response.created",')
    lines.append('            "response": {')
    lines.append('                "id": response_id,')
    lines.append('                "status": "in_progress",')
    lines.append('                "output": [],')
    lines.append('                "model": MODEL_ID,')
    lines.append('                "created_at": created_at,')
    lines.append("            },")
    lines.append("        }")
    lines.append("")
    lines.append("        output_index = 0")
    lines.append("        accumulated = []")
    lines.append("        final_output = []")
    lines.append("")
    lines.append("        # response.output_item.added (message)")
    lines.append("        yield {")
    lines.append('            "type": "response.output_item.added",')
    lines.append('            "output_index": output_index,')
    lines.append('            "item": {"type": "message", "role": "assistant", "content": []},')
    lines.append("        }")
    lines.append("")
    lines.append("        # response.content_part.added")
    lines.append("        yield {")
    lines.append('            "type": "response.content_part.added",')
    lines.append('            "output_index": output_index,')
    lines.append('            "content_index": 0,')
    lines.append('            "part": {"type": "output_text", "text": ""},')
    lines.append("        }")
    lines.append("")
    lines.append("        # Stream agent events via the shared streaming core.")
    lines.append("        # NOTE: function_call.* deltas (tool_call_chunks, args streaming) are not")
    lines.append("        # surfaced — process_turn_streaming exposes only text tokens. Tool calls")
    lines.append("        # still execute server-side via langgraph; their results are reflected in")
    lines.append("        # the final response_text but do not produce mid-stream function_call events.")
    lines.append("        metadata = {")
    lines.append('            "sessionId": thread_id,')
    lines.append('            "user_id": user_id,')
    lines.append('            "project_id": project_id,')
    lines.append("        }")
    lines.append("        async for ev in process_turn_streaming(")
    lines.append("            '', metadata,")
    lines.append("            messages=input_messages, task_id=response_id,")
    lines.append("        ):")
    lines.append('            if ev.type == "token":')
    lines.append("                accumulated.append(ev.text)")
    lines.append("                yield {")
    lines.append('                    "type": "response.output_text.delta",')
    lines.append('                    "output_index": output_index,')
    lines.append('                    "content_index": 0,')
    lines.append('                    "delta": ev.text,')
    lines.append("                }")
    lines.append('            elif ev.type == "interrupt":')
    lines.append("                # Interrupt: surface as final text + close.")
    lines.append("                accumulated.append(ev.text)")
    lines.append("                yield {")
    lines.append('                    "type": "response.output_text.delta",')
    lines.append('                    "output_index": output_index,')
    lines.append('                    "content_index": 0,')
    lines.append('                    "delta": ev.text,')
    lines.append("                }")
    lines.append("                break")
    lines.append('            elif ev.type == "final":')
    lines.append("                break")
    lines.append("")
    lines.append("        # response.output_text.done")
    lines.append("        full_text = ''.join(accumulated)")
    lines.append("        yield {")
    lines.append('            "type": "response.output_text.done",')
    lines.append('            "output_index": 0,')
    lines.append('            "content_index": 0,')
    lines.append('            "text": full_text,')
    lines.append("        }")
    lines.append("")
    lines.append(
        "        final_output = [ResponseOutput(type='message', role='assistant', content=full_text)]"
    )
    lines.append("")
    lines.append("        # response.completed")
    lines.append("        yield {")
    lines.append('            "type": "response.completed",')
    lines.append('            "response": {')
    lines.append('                "id": response_id,')
    lines.append('                "status": "completed",')
    lines.append(
        '                "output": [o.model_dump() if hasattr(o, "model_dump") else o for o in final_output],'
    )
    lines.append('                "model": MODEL_ID,')
    lines.append('                "created_at": created_at,')
    lines.append("            },")
    lines.append("        }")
    lines.append("")
    lines.append("        if store:")
    lines.append("            self._response_store[response_id] = {")
    lines.append("                'id': response_id,")
    lines.append("                'status': 'completed',")
    lines.append("                'output': final_output,")
    lines.append("                'model': MODEL_ID,")
    lines.append("                'stored': True,")
    lines.append("                'thread_id': config['configurable']['thread_id'],")
    lines.append("                'last_input_tokens': None,")
    lines.append("                'created_at': created_at,")
    lines.append("            }")
    lines.append("")
    lines.append('        yield "[DONE]"')
    lines.append("")

    return "\n".join(lines)
