"""Vystak — declarative AI agent orchestration."""

__version__ = "0.1.0"

# Channel plugin registry
from vystak.channels import (
    ChannelPluginRegistry,
    get_plugin,
    list_plugins,
    register_plugin,
)

# Hash engine
from vystak.hash import (
    AgentHashTree,
    ChannelHashTree,
    hash_agent,
    hash_channel,
    hash_dict,
    hash_model,
)

# Provider ABCs and supporting types
from vystak.providers import (
    AgentStatus,
    ChannelPlugin,
    DeployPlan,
    DeployResult,
    FrameworkAdapter,
    GeneratedCode,
    PlatformProvider,
    ValidationError,
)

# Provisioning engine
from vystak.provisioning import (
    CommandHealthCheck,
    CycleError,
    HealthCheck,
    HttpHealthCheck,
    NoopHealthCheck,
    Provisionable,
    ProvisionError,
    ProvisionGraph,
    ProvisionResult,
    TcpHealthCheck,
)
from vystak.schema import (
    Agent,
    AgentProtocol,
    Cache,
    Channel,
    ChannelType,
    Database,
    Embedding,
    HttpConfig,
    McpServer,
    McpTransport,
    Model,
    NamedModel,
    NatsConfig,
    ObjectStore,
    Platform,
    Policy,
    Postgres,
    Provider,
    Qdrant,
    Queue,
    Redis,
    Resource,
    RuntimeMode,
    Secret,
    Service,
    ServiceBusConfig,
    SessionStore,
    Skill,
    SkillRequirements,
    SlackChannelOverride,
    Sqlite,
    Transport,
    TransportConfig,
    TransportConnection,
    TransportType,
    Vault,
    VaultMode,
    VaultType,
    VectorStore,
    Workspace,
    WorkspaceType,
)

# Loader
from vystak.schema.loader import dump_agent, load_agent

__all__ = [
    "__version__",
    "Agent",
    "AgentProtocol",
    "Cache",
    "Channel",
    "ChannelType",
    "Database",
    "Embedding",
    "McpServer",
    "McpTransport",
    "Model",
    "NamedModel",
    "ObjectStore",
    "Platform",
    "Postgres",
    "Provider",
    "Qdrant",
    "Queue",
    "Redis",
    "Resource",
    "Policy",
    "SlackChannelOverride",
    "RuntimeMode",
    "Secret",
    "Service",
    "SessionStore",
    "Skill",
    "SkillRequirements",
    "Sqlite",
    "Vault",
    "VaultMode",
    "VaultType",
    "VectorStore",
    "Workspace",
    "WorkspaceType",
    "HttpConfig",
    "NatsConfig",
    "ServiceBusConfig",
    "Transport",
    "TransportConfig",
    "TransportConnection",
    "TransportType",
    "AgentHashTree",
    "ChannelHashTree",
    "hash_agent",
    "hash_channel",
    "hash_dict",
    "hash_model",
    "ChannelPluginRegistry",
    "get_plugin",
    "list_plugins",
    "register_plugin",
    "dump_agent",
    "load_agent",
    "AgentStatus",
    "ChannelPlugin",
    "DeployPlan",
    "DeployResult",
    "FrameworkAdapter",
    "GeneratedCode",
    "PlatformProvider",
    "ValidationError",
    "CommandHealthCheck",
    "CycleError",
    "HealthCheck",
    "HttpHealthCheck",
    "NoopHealthCheck",
    "Provisionable",
    "ProvisionError",
    "ProvisionGraph",
    "ProvisionResult",
    "TcpHealthCheck",
]
